name: Sync to Hugging Face hub

on:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
        run: |
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO_CLONE_URL: ${{ secrets.HF_REPO_CLONE_URL }}
        run: |

          # Add the Hugging Face remote with the correct URL
          git remote add hub $HF_REPO_CLONE_URL

          # Fetch the remote repository
          git fetch hub

          # Push to the 'main' branch forcefully
          git push --force hub main
